# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Releases our app to TestFlight"
  lane :release_app do
    export_app
    upload_app
  end

  desc "To export our app"
  lane :export_app do
    gym(
      project: "TestCICD.xcodeproj",
      scheme: "TestCICD",
      clean: true,
      export_xcargs: "-allowProvisioningUpdates",
      output_name: "ReleaseApp.ipa",
      xcargs: "-showBuildTimingSummary",
      verbose: true
    )
  end

  desc "To upload app to TestFlight"
  lane :upload_app do
    deliver(
      ipa: "ReleaseApp.ipa",
      skip_screenshots: true,
      skip_metadata: true,
      skip_app_version_update: true,
      force: true,
      submit_for_review: false,       # prevents full App Store review
      distribute_external: false,     # internal TestFlight testers only
      automatic_release: true         # make it immediately available
    )
  end

end